### ISSUE TITLE
how to delete all cookies exept for some doamins?

### ISSUE THREAD

**Issue by rezad1393** [jrie/flagCookies#1]
I thought the profile mode applied with global mode would keep the domains that are specified but it still deletes those cookies as well.
I dont want to check the key icons on all the cookies that I need for every domain that I need.

**Comment by jrie** [comment]
Hi, the profile mode will only protect cookies, if they are "keyed" and set as profile cookies.
Simply activating "profile mode" is not enough at the moment to decide which cookies should not be removed.

What would be possible to add as a feature - if no cookies are set to be keyed - profile mode will treat the particular (sub)domain as "profile domain" - and protect cookies for this sub- _or _ main domain cookies from being removed even so "global mode" is active.

Would this be already useful to you?

The only think to keep in mind about that feature, this will allow tracking cookies, if used by the website - so the suggested way would be to "key" the cookies you want to keep. As for a second point, setting a "profile domain" will only be valid for the domain it was set on, in case of a subdomain, this decision would only be valid for that subdomain, but not the main domain.

**Comment by rezad1393** [comment]
thanks for the answer.
Right now I have "cookie autodelete" addon. is does what I described but doesnt have individual cookie managment like yours.
I like to have both, so for example on github that I am logged in I would keep all(or most iwth the help of your addon) but on youtube I would not keep any except some like the wide-video or consent cookie and delete the use id and other cookies of youtube.

**Comment by jrie** [comment]
@rezad1393 
> for example on github that I am logged in I would keep all(or most iwth the help of your addon)

You can do so by "keying" the appropriate cookies. But I will try to implement a feature, where you can keep "all" relevant cookies for github simply by selectiing/activating "profile" mode, instead of picking particular cookies to keep

> on youtube I would not keep any except some like the wide-video or consent cookie and delete the use id and other cookies of youtube.

As mentioned, you can do so by using the "keying" icon. But there is no suggestion what to keep or not to keep and what not.

Does this answer your needs?

I agree, having a "profile" mode for a domain, excluding it from "global" mode, will be very useful.
So I will assign this as a "feature request" and try to implement it in the next version.

**Comment by jrie** [comment]
A version is released on https://addons.mozilla.org/en-US/firefox/addon/flag-cookies/ which gives the option to:
When global or auto-flag is active and profile mode is enabled, and no cookies are keyed as profile cookies, cookies for the (sub)domains are protected from removal. But third party cookies will be removed still to avoid tracking.

**Comment by rezad1393** [comment]
Hi
I installed your addon and removed my other cookie manager addon (it seemed that youtube could track me with that installed.)

now their are some issue I have with this addon that are somewhat related to this issue but not that much related. should I open new issues?

**Comment by jrie** [comment]
I think your initial request was a feature request, a _global_ "domain profile mode", which I think is implemented, correct? - So I would close this issue then and suggest opening new issues.

**Comment by jrie** [comment]
Closing the issue, since the initial request seems to be satisfied.
