### ISSUE TITLE
FlagCookies is missing cookies when used in incognito/private tabs

### ISSUE THREAD

**Issue by pspzockerscene** [jrie/flagCookies#10]
This is just a public ticket for a problem which I've reported back in may of 2024 via private message just to have it here in the repo too so that it is publicly visible.

In some cases when exporting cookies in incognito/private tabs, some cookies are missing.

**OS:** Windows 10
**Browser:** Chrome Version 125.0.6422.77 (Offizieller Build) (64-Bit)
**FlagCookies Version:** 3.6.0
**Webseites:** seedr.cc, Also reproducible with: adulttime.com [I can't provide an account for this website]

More information and test data: Sent to FlagCookies developer via private message.

**Comment by jrie** [comment]
Hello @pspzockerscene - can you review this issue with the latest version of the addon from this repository?
I made some tests and of what I saw everything is detected on `seedr.cc`.

**Comment by pspzockerscene** [comment]
Test with dev build or wait for release and then test?

**Comment by jrie** [comment]
Please test with the dev version in this repository. I would like to test in advance of a release.

**Comment by pspzockerscene** [comment]
3.6.2 doesn't work at all for me (tested in Chrome):
- Style looks broken
- Chrome warns about manifestV2
- I got zero exportable cookies

Tested in normal tab and incognito tab.
![2024-12-12 17_26_01-goo - Google Suche](https://github.com/user-attachments/assets/50d15af4-afb1-4ed2-9ef3-ac80e71d0f96)

**Comment by jrie** [comment]
You have to copy and rename the file:
manifest_v3_chrome_browsers.json (This is the one for Chrome)
to:
manifest.json (replace the existing one)

Then try to load the extension. It might be that you have to allow the addon in private/incognito tabs.

I will later on check also. Basically it should work.

**Comment by jrie** [comment]
@pspzockerscene - I tested using the `manifest_v3_chrome_browsers.json` to `manifest.json` and can load the addon in Chrome. Can you double check and confirm?

**Comment by pspzockerscene** [comment]
Sorry for my repeated stupidity!
Got the addon 3.6.1 working now.

**The issue looks to be fixed.**
I've only tested it with "seedr.cc" in a private tab and the addon got all cookies.

**Comment by jrie** [comment]
Good news, thank you! :+1: 

Closing this for now.

**Comment by pspzockerscene** [comment]
I will update [out instructions](https://support.jdownloader.org/de/knowledgebase/article/account-cookie-login-instructions) with a delay of 1+ weeks to make sure that users get that update beforehand.
When will it go public?

**Comment by jrie** [comment]
The update/new version is available in the Chrome webstore. But other publications should follow soon.

**Comment by pspzockerscene** [comment]
I've just removed the warning about this FlagCookies bug from our cookie login instructions.
