### ISSUE TITLE
The answer to "Getting file from file chooser after extension popup closed" seems no longer working.

### ISSUE THREAD

**Issue by Leslie-Wong-H** [jrie/flagCookies#2]
My reply is here:

[Firefos Add-on: Getting file from file chooser after extension popup closed](https://discourse.mozilla.org/t/getting-file-from-file-chooser-after-extension-popup-closed/32881)

**Comment by jrie** [comment]
Unfortunately this does not seem to be fixable on the addon end, therefore I added a fix by opening a subwindow, which stays open and a file can been chosen. So settings can be imported without trouble.
This is new in version 3.1.11.
