### ISSUE TITLE
Broken when FPI is enabled

### ISSUE THREAD

**Issue by tiagoapimenta** [jrie/flagCookies#4]
Is it possible to make the extension work even with `privacy.firstparty.isolate` set to `true`?

## Steps to Reproduce
* create new bare empty profile;
* open `about:config` and change the value of `privacy.firstparty.isolate` to `true`;
* install the extension `https://addons.mozilla.org/en-GB/firefox/addon/flag-cookies/`;
* open the extension popup via the unified extensions icon;
* select the mode `Global`;
* browse any website that contains cookies;
* open the extension popup again;

## Current Behavior
No cookie are shown

## Expected Behavior
Show cookies

## Information
Browser: Firefox 116.0.3 (64-bit)
flagCookies Version: 3.1.16  
OS: 6.5.3-1-edge

**Comment by jrie** [comment]
Hi. Showing cookies when firstpartyisolation is enabled is possible and I have been working on this.

The new version with corresponding changes will soon be live here, also with other changes and fixes.

I will comment here once updated to that version.

**Comment by jrie** [comment]
Hi @tiagoapimenta - the new version with the request "FirstPartyIsolation" is ready and live here at Github. Please check out the version and let me know if things work for you as expected.

**Comment by tiagoapimenta** [comment]
quick guide to help whoever else:
* install npm
* `npm install --global web-ext`
* `git clone https://github.com/jrie/flagCookies`
* `web-ext build --overwrite-dest --source-dir=flagCookies --artifacts-dir=.build`
* on Firefox open `about:debugging`, click on Firefox Icon, Load Temporary Add-on

About version 3.2.0:

With `privacy.firstparty.isolate` set to `false` looks like the extensions sometimes stay greyed and inaccessible.
![ss00](https://github.com/jrie/flagCookies/assets/715998/97451ee5-ad47-43bc-b121-1e5177ab84ca)

With `privacy.firstparty.isolate` set to `true` sometimes it shows partially the cookies, sometimes when you refresh the page it show a empty list, it's unstable behaviour.
![ss01](https://github.com/jrie/flagCookies/assets/715998/24c94700-041b-487a-bc55-702d8a7452e0)
![ss02](https://github.com/jrie/flagCookies/assets/715998/87cdedaf-7076-4ccf-aeae-374b4a03933c)

**Comment by jrie** [comment]
Hi. Thank you for your error report. Indeed there are these issues, I am working on bugfixes and changes.

I am trying to push out the new codebase soon, but this will take some time. Likely one and a half weeks.

Please be patient.

**Comment by jrie** [comment]
The new updated code base is online here at Github. This also should fix this issues you reported.

**Comment by tiagoapimenta** [comment]
Test plan:
* open a fresh Firefox instance with empty profile
* install the extension
* select the mode Global in the extension popup
* open google.com page
* it'll ask to accept cookies, select any reply (even if you reject, Google still saves a cookie to prevent it to asking again)
* refresh the page
* It's expected to ask to accept cookies again

When using Global mode with `privacy.firstparty.isolate` disabled it works as expected, but with `privacy.firstparty.isolate` the cookies are stored.

**Comment by jrie** [comment]
Thank you @tiagoapimenta for testing and reporting this issue. I will try to land a fix asap during the next few days and report back once ready.

**Comment by jrie** [comment]
There has been a update, with a lot of bugfixes, improvements, and additions.
This version also provides a fix when firstPartyIsolate is enabled @tiagoapimenta 

Please note, this version is at present only live at Github, not the extension stores.
