### ISSUE TITLE
Make container groups / contextual identities work (again)

### ISSUE THREAD

**Issue by jrie** [jrie/flagCookies#6]
Support for cookies in container groups / contextual identities support is broken at present.
This does affect Firefox.

**Comment by cheater** [comment]
how do you know it's broken? i thought you hadn't tested it?

btw the old version was able to work with Facebook Container.

**Comment by jrie** [comment]
> how do you know it's broken? i thought you hadn't tested it?

A Firefox user reported that containers are broken.

> btw the old version was able to work with Facebook Container.

Probably yes, in before the bigger update. But the newer versions will be lighter in RAM and CPU usage, so I would recommend to update once the bugs are fixed and landed in the addon stores.

I work on that, so it will hopefully be soon.

**Comment by cheater** [comment]
Looking forward to it! Thanks!

**Comment by jrie** [comment]
Update 3.4.0 landed some additions for container group handling.
