### ISSUE TITLE
Notifications sent when notifications are disabled.

### ISSUE THREAD

**Issue by Irmitya** [jrie/flagCookies#7]
[Chrome]
Preferences  >  FlagCookie settings > Display notifications:
I disable notifications. 
I often get a popup notification telling me the extension was updated.

**Comment by jrie** [comment]
Hello. A notification, despite notifications beeing  turned off, is only displayed once in two cases: The addon is installed the first time or when an update was installed. This is intended.  
Other times there should be no other notifications.

In case you receive other notifications, even they are not enabled, please note down the message, so I can check.

Does this answer your question?

**Comment by Irmitya** [comment]
Okay, then I request you add the option to also disable update notifications. 

I don't know what's being updated or when it's updated, and as long as it keeps working, I don't need to know. There's no option to disable automatic updates, and chrome doesn't allow users to block specific extension notifications. 

My only options are to 
1) disable **all** notifications from chrome, 
2) try to learn and compile it myself to remove auto updating, 
3) remove/disable the extension until if/when I need to use it
4) do nothing and keep getting notifications

**Comment by Irmitya** [comment]
Also, since that's intentional, what does [Disable Notifications] disable then? 
The only other notifications I'm aware of are displayed in the extension window and that doesn't disable those either.

**Comment by jrie** [comment]
I understand. I will add a option to disable update notifications in the settings.

For the time beeing, I am not able to make this addition during the very next days, but I will follow up.

**Comment by jrie** [comment]
> Also, since that's intentional, what does [Disable Notifications] disable then? The only other notifications I'm aware of are displayed in the extension window and that doesn't disable those either.

I hope I understand your question. By default notifications, addional ones, are not enabled in FlagCookies. But they can be enabled in the internal settings of the addon, in *Preferences*.

Disabling the notifications for the addon in the browser would only block the install and update notifications, which you noticed. Since, by default, only those are shown.

If you enable the optional notifications in *Preferences*,  more are displayed. For example the count of deleted cookies or other actions. As mentioned, those can optionally be turned on and off.

**Comment by Irmitya** [comment]
> If you enable the optional notifications in _Preferences_, more are displayed. For example the count of deleted cookies or other actions. As mentioned, those can optionally be turned on and off.

Got it, thanks.
