### ISSUE TITLE
Request: Export to Clipboard, remove post-confirmation

### ISSUE THREAD

**Issue by Irmitya** [jrie/flagCookies#8]
[Chrome]
When exporting to clipboard, a box pops up saying it was exported with an OK button. You can't just click somewhere else in the window, as the window is locked waiting for confirmation.

You can still use other windows in the browser but Chrome will lock that window as active and in front, so if you click on another program (such as JDownloader to paste the cookies), chrome will snap focus back to that window until you click OK.

**Comment by jrie** [comment]
The confirmation dialog has the purpose to visually display the user that the action was successfull or in case of errors show this.

I understand this might be somehow disturbing, since the browser tab is locked due to the dialog, until confirmed, but I am not aware of other solutions on how to provide this information.

**Comment by Irmitya** [comment]
EditThisCookie displays a little textbox for a few seconds before disappearing. 
You could also display text in that big empty space to the left under Export expired cookies.

**Comment by jrie** [comment]
> EditThisCookie displays a little textbox for a few seconds before disappearing. You could also display text in that big empty space to the left under Export expired cookies.

I will check out on what I can do about that and if something like that can be included in FlagCookies. Thank you for the suggestion, much appreciated!

**Comment by jrie** [comment]
In the the commit e6d3764a643889eb67925a1220d1e8ba9cd8a8f8 the "window.alert" functions are removed from cookie to clipboard, and browser notifications are displayed instead. This way it is ensured, the information is visible about success or on failure.
